REQUIRED_SECTIONS = [
    "Position",
    "Department",
    "Reports To",
    "Collaborates With",
    "Mission",
    "Responsibilities",
    "Skills",
    "Tools",
    "Knowledge Sources",
    "Memory Access",
    "Tool Access Level",
    "Inputs",
    "Input Validation Rules",
    "Outputs",
    "Output Quality Checklist",
    "Review Checklist",
    "Decision Authority",
    "Approval Level",
    "Risk Level",
    "Escalation Rules",
    "Escalation Message Template",
    "Failure Response",
    "Forbidden Actions",
    "Common Mistakes To Avoid",
    "Performance Metrics",
    "Example Tasks",
    "Example Good Output",
    "Example Bad Output",
    "Version",
    "Last Updated",
]
