#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = ROOT / "apps" / "brain"
venv_site_packages = sorted((APP_ROOT / "venv" / "lib").glob("python*/site-packages"))
for path in venv_site_packages:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))
if str(APP_ROOT) not in sys.path:
    sys.path.insert(0, str(APP_ROOT))

from app.business_automation import business_automation  # noqa: E402


def main() -> int:
    company = f"CLI Co {uuid.uuid4().hex[:6]}"
    lead = business_automation.create_lead(
        name="CLI User",
        company=company,
        service_interest="Website redesign and SEO",
        budget=275000,
        channel="website",
        notes="Generated by CLI verification.",
    )
    proposal = business_automation.create_proposal(
        client_name=company,
        project_name="CLI Growth Sprint",
        scope="Website redesign and SEO",
        timeline_weeks=6,
        budget_estimate=310000,
        lead_id=lead["id"],
    )
    quotation = business_automation.create_quotation(
        proposal_id=proposal["id"],
        labor_hours=80,
        hourly_rate=6000,
        expenses=15000,
        discount=10000,
    )
    payload = {
        "lead": lead,
        "proposal": proposal,
        "quotation": quotation,
        "analytics": business_automation.analytics(),
    }
    print(json.dumps(payload, ensure_ascii=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
